apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eth-balance.fullname" . }}
  labels:
    {{- include "eth-balance.labels" . | nindent 4 }}
type: Opaque
data:
  api_key: {{ .Values.api_key | b64enc | quote }}