name: Publish Helm Chart

on:
  push:
    tags: [ 'v*.*.*' ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  CHART_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: azure/setup-helm@v4.2.0
        id: helm-install
 
      - name: Helm registry login
        run: |
          helm registry login \
            --username ${{ github.actor }} \
            --password ${{ secrets.GITHUB_TOKEN }} \
          ${{ env.REGISTRY }}

      - name: Helm release
        id: helm-release
        run: |
          helm package ./helm --version ${{ github.ref_name }} -d tmp/package
          echo "package=$(ls tmp/package/*.tgz)" >> $GITHUB_OUTPUT

      - name: Helm Publish
        id: helm-publish
        run: helm push ${{steps.helm-release.outputs.package}} oci://${{ env.REGISTRY }}/charts/${{ env.CHART_NAME }}

      - name: Attest
        uses: actions/attest-build-provenance@v1
        id: attest
        with:
          subject-path: ${{steps.helm-release.outputs.package}}
